### ISSUE TITLE
onverwachte invalidParams bij ongeldige kadasternatuurlijkpersoonidentificatie

### ISSUE THREAD

**Issue by fsamwel** [kadaster/BRK-bevragen#865]
/kadasternatuurlijkpersonen/1234567890123456789012345678901234567890123456789012345678901 geeft nu in het antwoord:
```
    "invalidParams": [
        {
            "name": "kadasternatuurlijkpersoonidentificatie",
            "code": "maxLength",
            "reason": "Waarde is langer dan maximale lengte 60."
        },
        {
            "name": "kadaster__natuurlijk__persoon__identificatie",
            "code": "maxLength",
            "reason": "Waarde is langer dan maximale lengte 60."
        }
    ]
```

De tweede parameter bestaat niet, verwijst waarschijnlijk naar dezelfde parameter als de eerste parameter. Is dubbel.

N.B. tot vorige release werd alleen de eerste invalidParam gegeven.

**Comment by kad-hebbim** [comment]
Opgelost. Komt door camelcase verandering in de openapi.yaml van de pad parameters.
Hierdoor krijg je nu de laatste invalidParam melding terug.

**Comment by fsamwel** [comment]
@kad-hebbim ik krijg dit nu ook bij niet-natuurlijk persoon:
```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Een of meerdere parameters zijn niet correct.",
    "status": 400,
    "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
    "instance": "/kadasternatuurlijkpersonen/1234567890123456789012345678901234567890123456789012345678901",
    "code": "paramsValidation",
    "invalidParams": [
        {
            "name": "kadaster__natuurlijk__persoon__identificatie",
            "code": "maxLength",
            "reason": "Waarde is langer dan maximale lengte 60."
        }
    ]
}
```

**Comment by fsamwel** [comment]
@kad-hebbim deze naam met underscores erin is juist niet degene die ik zou verwachten. In de specificaties heet deze namelijk "kadasterNatuurlijkPersoonIdentificatie" of "kadasterNietNatuurlijkPersoonIdentificatie".

Ik zou dus bij een natuurlijk persoon met onjuiste identificatie verwachten:
    "invalidParams": [
        {
            "name": "kadasterNatuurlijkPersoonIdentificatie",
            "code": "maxLength",
            "reason": "Waarde is langer dan maximale lengte 60."
        }
    ]

**Comment by kad-hebbim** [comment]
Opgelost in code.
